// Generated by CoffeeScript 1.4.0
(function() {

  $(function() {
    $('#loading').hide();
    $('#done').hide();
    $('input[type=file]').bind('click', function() {
      $('#upload').hide();
      return $('#loading').show();
    });
    return $('input[type=file]').bind('change', function() {
      $('#loading').hide();
      $('#done').show();
      return $('#done').html($(this).val());
    });
  });

}).call(this);
